### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by btopro** [dmd-program/dmd-course-materials#22]
What's the license of this?

**Comment by michael-collins** [comment]
Oer schema will be providing licences for content throughout the materials.
Some is teach act, some is cc-by-nc-sa.

**Comment by btopro** [comment]
can you include a license.md explaining this? I'm sure others will have this.

**Comment by michael-collins** [comment]
As an example, [this page](https://dmd-program.gitbooks.io/dmd-100-sp17/content/topics/what_is_design.html) has some OER Schema applied, which references a CC-BY license.

Will write a [short explanation here](https://dmd-program.gitbooks.io/dmd-100-sp17/content/license.html) for now.

**Comment by btopro** [comment]
just add a LICENSE.MD to the top of the repo like a normal person ;)

**Comment by michael-collins** [comment]
Okay, done. I switched repos. This is the latest working repo: https://github.com/dmd-program/dmd-100-sp17
